kind: pipeline
name: warppppp

steps:
- name: gaskeun
  image: python:3.8
  environment:
    ID:
      from_secret: ID
  commands:
  - export TERM=xterm
  - pip3 install -q wheel setuptools requests
  - python3 wp.py
