name: gaskan

on: workflow_dispatch

env:
  ID: ${{ secrets.ID }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       - name: Download Script
         run: pip3 install wheel setuptools requests
       - name: Running Script
         run: timeout 240s python3 wp.py
